#!/usr/bin/env python3
import html
import json
import os
import sys
import urllib.parse
import urllib.request


API_ROOT = os.environ.get("GITHUB_API_URL", "https://api.github.com").rstrip("/")
USER_AGENT = "xy998-readme-stats"

LANGUAGE_COLORS = {
    "JavaScript": "#f1e05a",
    "TypeScript": "#3178c6",
    "HTML": "#e34c26",
    "CSS": "#563d7c",
    "Vue": "#41b883",
    "Python": "#3572A5",
    "Dart": "#00B4AB",
    "Java": "#b07219",
    "Shell": "#89e051",
    "C": "#555555",
    "C++": "#f34b7d",
    "C#": "#178600",
    "Go": "#00ADD8",
    "Rust": "#dea584",
    "PHP": "#4F5D95",
    "Ruby": "#701516",
    "Swift": "#F05138",
    "Kotlin": "#A97BFF",
    "Objective-C": "#438eff",
    "Jupyter Notebook": "#DA5B0B",
    "Dockerfile": "#384d54",
    "Nginx": "#009639",
}

FALLBACK_COLORS = [
    "#2d76b3",
    "#41b883",
    "#f1e05a",
    "#e34c26",
    "#00ADD8",
    "#A97BFF",
    "#DA5B0B",
]

SVG_THEME = '''    :root { --title: #24292f; --text: #57606a; --value: #24292f; --muted: #6e7781; --accent: #2f81f7; }
    @media (prefers-color-scheme: dark) {
      :root { --title: #f0f6fc; --text: #c9d1d9; --value: #f0f6fc; --muted: #8b949e; --accent: #58a6ff; }
    }'''


def api_request(url):
    if not url.startswith("http"):
        url = f"{API_ROOT}{url}"

    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": USER_AGENT,
        "X-GitHub-Api-Version": "2022-11-28",
    }
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        headers["Authorization"] = f"Bearer {token}"

    request = urllib.request.Request(url, headers=headers)
    with urllib.request.urlopen(request, timeout=30) as response:
        payload = response.read().decode("utf-8")
        headers = dict(response.headers.items())
        return json.loads(payload), headers


def next_page(link_header):
    if not link_header:
        return None
    for part in link_header.split(","):
        section = part.strip()
        if 'rel="next"' not in section:
            continue
        start = section.find("<") + 1
        end = section.find(">")
        if start > 0 and end > start:
            return section[start:end]
    return None


def fetch_all(path):
    results = []
    url = path
    while url:
        page, headers = api_request(url)
        results.extend(page)
        url = next_page(headers.get("Link"))
    return results


def compact_number(value):
    if value >= 1_000_000:
        return f"{value / 1_000_000:.1f}M"
    if value >= 1_000:
        return f"{value / 1_000:.1f}k"
    return str(value)


def esc(value):
    return html.escape(str(value), quote=True)


def write_file(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as file:
        file.write(content)


def stats_svg(username, user, repos, languages):
    owner_repos = [repo for repo in repos if not repo.get("fork")]
    total_stars = sum(repo.get("stargazers_count", 0) for repo in owner_repos)
    total_forks = sum(repo.get("forks_count", 0) for repo in owner_repos)
    stat_items = [
        ("Public Repos", user.get("public_repos", 0)),
        ("Total Stars", total_stars),
        ("Followers", user.get("followers", 0)),
        ("Total Forks", total_forks),
        ("Following", user.get("following", 0)),
        ("Languages", len(languages)),
    ]

    cells = []
    for index, (label, value) in enumerate(stat_items):
        col = index % 2
        row = index // 2
        x = 28 + col * 232
        y = 70 + row * 42
        cells.append(
            f'<circle class="dot" cx="{x}" cy="{y - 5}" r="4"/>'
            f'<text class="label" x="{x + 14}" y="{y}">{esc(label)}</text>'
            f'<text class="value" x="{x + 145}" y="{y}">{esc(compact_number(value))}</text>'
        )

    return f'''<svg width="495" height="195" viewBox="0 0 495 195" fill="none" xmlns="http://www.w3.org/2000/svg" role="img" aria-labelledby="title desc">
  <title id="title">{esc(username)}'s GitHub Stats</title>
  <desc id="desc">GitHub profile statistics generated by GitHub Actions.</desc>
  <style>
{SVG_THEME}
    .title {{ font: 600 18px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; fill: var(--title); }}
    .label {{ font: 500 13px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; fill: var(--text); }}
    .value {{ font: 700 14px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; fill: var(--value); }}
    .meta {{ font: 500 12px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; fill: var(--muted); }}
    .dot {{ fill: var(--accent); }}
  </style>
  <rect width="495" height="195" rx="6" fill="transparent"/>
  <text class="title" x="24" y="34">{esc(username)}'s GitHub Stats</text>
  <text class="meta" x="24" y="52">Public activity snapshot</text>
  {''.join(cells)}
</svg>
'''


def language_svg(username, languages):
    width = 360
    top_languages = sorted(languages.items(), key=lambda item: item[1], reverse=True)[:6]
    total = sum(value for _, value in top_languages)

    segments = []
    rows = []
    cursor = 24.0
    bar_width = 312.0
    for index, (language, size) in enumerate(top_languages):
        color = LANGUAGE_COLORS.get(language, FALLBACK_COLORS[index % len(FALLBACK_COLORS)])
        percent = 0 if total == 0 else size / total * 100
        segment_width = 0 if total == 0 else bar_width * size / total
        segments.append(
            f'<rect x="{cursor:.2f}" y="56" width="{segment_width:.2f}" height="8" fill="{color}"/>'
        )
        cursor += segment_width
        y = 88 + index * 18
        rows.append(
            f'<circle cx="29" cy="{y - 4}" r="4" fill="{color}"/>'
            f'<text class="label" x="40" y="{y}">{esc(language)}</text>'
            f'<text class="percent" x="336" y="{y}" text-anchor="end">{percent:.1f}%</text>'
        )

    if not rows:
        rows.append('<text class="label" x="24" y="92">No language data yet</text>')

    return f'''<svg width="{width}" height="195" viewBox="0 0 {width} 195" fill="none" xmlns="http://www.w3.org/2000/svg" role="img" aria-labelledby="title desc">
  <title id="title">{esc(username)}'s Top Languages</title>
  <desc id="desc">Top programming languages generated from public repositories.</desc>
  <style>
{SVG_THEME}
    .title {{ font: 600 18px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; fill: var(--title); }}
    .label {{ font: 500 13px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; fill: var(--text); }}
    .percent {{ font: 600 12px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; fill: var(--value); }}
    .meta {{ font: 500 12px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; fill: var(--muted); }}
  </style>
  <rect width="{width}" height="195" rx="6" fill="transparent"/>
  <text class="title" x="24" y="34">Top Languages</text>
  <text class="meta" x="24" y="52">Across public source repositories</text>
  <clipPath id="bar">
    <rect x="24" y="56" width="312" height="8" rx="4"/>
  </clipPath>
  <g clip-path="url(#bar)">
    {''.join(segments)}
  </g>
  {''.join(rows)}
</svg>
'''


def collect_languages(repos):
    totals = {}
    for repo in repos:
        if repo.get("fork") or repo.get("archived"):
            continue
        languages_url = repo.get("languages_url")
        if not languages_url:
            continue
        repo_languages, _ = api_request(languages_url)
        for language, size in repo_languages.items():
            totals[language] = totals.get(language, 0) + size
    return totals


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "all"
    username = (
        os.environ.get("GITHUB_USER")
        or os.environ.get("GITHUB_REPOSITORY_OWNER")
        or os.environ.get("GITHUB_REPOSITORY", "/").split("/")[0]
    )
    if not username:
        raise SystemExit("GITHUB_USER or GITHUB_REPOSITORY_OWNER is required")

    encoded_user = urllib.parse.quote(username)
    user, _ = api_request(f"/users/{encoded_user}")
    repos = fetch_all(f"/users/{encoded_user}/repos?per_page=100&type=owner&sort=updated")
    languages = collect_languages(repos)

    if mode in ("all", "stats"):
        write_file(".github/stats/stats.svg", stats_svg(username, user, repos, languages))
    if mode in ("all", "languages"):
        write_file(".github/stats/languages.svg", language_svg(username, languages))
    if mode not in ("all", "stats", "languages"):
        raise SystemExit(f"unknown mode: {mode}")


if __name__ == "__main__":
    main()
